gridgain/python-thin-client

pygridgain/api/sql.py, tests/test_sql.py
(cherry picked from commit 4b60f30f73f6a7f3703c7fe4d5aa40339b6d1c25)
=> GG-32661 [IGNITE-12809] Fix wrong order of the SQL query result

pygridgain/api/sql.py, pygridgain/utils.py
(cherry picked from commit d7d6d35d906cebc2f69e63e18f6ae8b1abe76132)
=> GG-32601 [IGNITE-11528]: Deprecate SqlQuery API

pygridgain/client.py
(cherry picked from commit 0f2828b521aa7bf93cfdcd5302bb77434fffe1e0)
=> GG-28235 [IGNITE-14127] Default sql page size from 1 => 1024

pygridgain/client.py, tests/test_binary.py
(cherry picked from commit 83208c2ef87d5b241c45dd5fd8f5ec4b58e2a8df)
=> GG-32600 [IGNITE-12975] SQL query do not create cache

pygridgain/api/binary.py, pygridgain/datatypes/complex.py, pygridgain/queries/__init__.py, pygridgain/queries/query.py, pygridgain/queries/response.py
(cherry picked from commit c746329f9148e84ab15268a9d15c0587f9b9e19a)
=> GG-32680 [IGNITE-14072] Refactor and optimize Response and SQLResponse

pygridgain/queries/response.py, tests/config/ignite-config.xml.jinja2, tests/test_affinity_request_routing.py
(cherry picked from commit ba268ccbc747cc667eca2722c646b9395276e738)
=> GG-32679 [IGNITE-14154] Remove unnecessary test, remove duplicates

.gitignore, MANIFEST.in, README.md, cext/cutils.c, pygridgain/api/binary.py, pygridgain/utils.py, requirements/install.txt, scripts/build_wheels.sh, scripts/create_distr.sh, scripts/create_sdist.sh, setup.py, tests/conftest.py, tests/test_cutils.py
(cherry picked from commit e5ca3fceb79a6c2e01c7480e56df162088fbedc0)
=> GG-32909 IGNITE-14186 Implement C module to speedup hashcode

.travis.yml, pygridgain/cache.py, tests/affinity/conftest.py, tests/affinity/test_affinity_bad_servers.py
on failed node
(cherry picked from commit 6f56a3bf30f98c2a960d6f909f97bd2094e64473)
=> GG-32907 [IGNITE-14245] Fix infinite loop while trying to get affinity mapping

pygridgain/aio_cache.py, pygridgain/aio_client.py, pygridgain/cache.py, pygridgain/client.py, tests/affinity/test_affinity.py, tests/affinity/test_affinity_request_routing.py, tests/common/test_cache_class.py, tests/common/test_cache_size.py, tests/util.py
(cherry picked from commit 7cbfe324eb2fb16335b51191cbed9b0e1dc8c88d)
=> GG-32981 [IGNITE-14444] Move affinity mapping to clients

pygridgain/binary.py, pygridgain/connection/aio_connection.py, pygridgain/connection/connection.py, pygridgain/datatypes/internal.py, pygridgain/datatypes/null_object.py, pygridgain/datatypes/standard.py, pygridgain/queries/query.py, pygridgain/queries/response.py, pygridgain/stream/binary_stream.py
(cherry picked from commit e48f4bea7f91325ad1e07056c9d236008b91ee7e)
=> GG-32996 [IGNITE-14472] Multiple performance improvements

pygridgain/binary.py, pygridgain/datatypes/base.py, pygridgain/datatypes/cache_properties.py, pygridgain/datatypes/complex.py, pygridgain/datatypes/internal.py, pygridgain/datatypes/primitive.py, pygridgain/datatypes/primitive_arrays.py, pygridgain/datatypes/primitive_objects.py, pygridgain/datatypes/standard.py, pygridgain/queries/response.py, tests/common/test_datatypes.py, tests/common/test_key_value.py, tests/common/test_sql.py
(cherry picked from commit 3586db7c30e22aff61d2251fec1ffaa355b4c599)
=> GG-33810 [IGNITE-14511] Fix serialization of bytes, improve serialization-deserialization of collections

README.md, scripts/BuildWheels.ps1
(cherry picked from commit 453ea5d9cf9a8c0ebb6aa92d8268f02d195230d5)
=> GG-33813 [IGNITE-14534] Add script to build wheels on Windows

MANIFEST.in, examples/docker-compose.yml, examples/readme.md, setup.py, tests/affinity/test_affinity_request_routing.py
(cherry picked from commit 8b1e61c87e423058a23112ceade542465d8f710f)
=> GG-33815 [IGNITE-14564] Add LICENSE files to all artifacts

pygridgain/aio_client.py, pygridgain/client.py, pygridgain/datatypes/base.py, pygridgain/datatypes/cache_properties.py, pygridgain/datatypes/complex.py, pygridgain/datatypes/expiry_policy.py, pygridgain/datatypes/internal.py, pygridgain/datatypes/null_object.py, pygridgain/datatypes/primitive.py, pygridgain/datatypes/primitive_arrays.py, pygridgain/datatypes/primitive_objects.py, pygridgain/datatypes/standard.py, pygridgain/queries/response.py, pygridgain/utils.py, tests/common/test_binary.py, tests/common/test_datatypes.py, tests/common/test_key_value.py
(cherry picked from commit 746dd1315a0a86d8f1c501d80f3a91dfafd0f648)
=> GG-33820 [IGNITE-14705] Fix handling collections with binary objects

requirements/install.txt, requirements/setup.txt, setup.py, tests/common/test_expiry_policy.py
(cherry picked from commit 8c8a006a0b0e913f9d38dd45dab80001b144c3c6)
=> GG-33848 [IGNITE-14738] Remove obsolete dependency to pytest-runner

pygridgain/aio_cache.py, pygridgain/cache.py
Signed-off-by: Ivan Daschinsky <ivandasch@apache.org>
(cherry picked from commit fa364dfd1079571a93299f2b1289a4993290b0c4)
=> GG-33856 IGNITE-14686 Fix incorrect type hint for get_all

docs/async_examples.rst, docs/datatypes/cache_props.rst, docs/examples.rst, examples/transactions.py, tests/common/test_transactions.py
(cherry picked from commit a53afcccb6c14b119a4d258da03d7d72445f62d5)
=> GG-33875 [IGNITE-14850] Document Transactions API

docs/async_examples.rst, docs/examples.rst, examples/expiry_policy.py, examples/transactions.py, pygridgain/aio_client.py, pygridgain/cache.py, pygridgain/client.py, pygridgain/datatypes/cache_properties.py, pygridgain/datatypes/expiry_policy.py, pygridgain/transaction.py, tests/common/test_expiry_policy.py, tests/common/test_transactions.py
Add support for datetime.timedelta for expiry_policy
(cherry picked from commit 92a115cf450a71d811dc1af684b3ba7fa04a98f2)
=> GG-33908 IGNITE-14911 Unify timeouts

pygridgain/connection/aio_connection.py, pygridgain/connection/connection.py, pygridgain/connection/protocol_context.py, pygridgain/queries/query.py, tests/conftest.py, tests/security/test_auth.py, tests/security/test_ssl.py
(cherry picked from commit 8fc14f874e6cd2f144b4fe3f4029bd46d8defe09)
=> GG-33923 IGNITE-15103 Implement logging of connections and queries

pygridgain/utils.py, tests/common/test_datatypes.py
(cherry picked from commit be18440ea2d81a053ad8a8d031bf1652f0b8e92a)
=> GG-33663 IGNITE-15266 Fix nested object arrays deserialization

pygridgain/connection/connection.py, tests/__init__.py, tests/common/test_sync_socket.py
(cherry picked from commit 3bf1cc1ad9e56a3b74a9abbb8a586495afb40169)
=> GG-33808 IGNITE-15479 Fix partial read from socket

pygridgain/aio_cache.py, pygridgain/api/sql.py, pygridgain/cache.py, pygridgain/cursors.py, requirements/install.txt
Updated all the method signatures to include threshold leading upto the actual queryVector method
=> GG-41265 Introduced a threshold in Vector Search

scripts/build_wheels.sh, scripts/create_distr.sh, scripts/create_sdist.sh
https://ggsystems.atlassian.net/browse/GG-41889
=> GG-41889 Update release building scripts

.readthedocs.yaml, requirements/docs.txt
https://ggsystems.atlassian.net/browse/GG-41905
=> GG-41905 Add .readthedocs.yaml
